<a href="https://colab.research.google.com/github/obidjonqunduzov/data-science/blob/main/11_Numpy_files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy kutubxonasidagi fayllar bilan ishlashni ko'ramiz

In [ ]:
import numpy as np

In [ ]:
array_1 = np.arange(10)
array_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.save('array_arange', array_1) # array_1 massivini 'array_arange fayiliga yuklab oldek

In [ ]:
read_array_1 = np.load('array_arange.npy') # yuklab olgan faylimizni read_array_1 o'zgaruvchisiga yuklab oldek
read_array_1 # va usha fayilni ochamiz

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array_2 = np.random.randn(4,3)
array_2

array([[ 0.74686603, -0.45180601, -0.11406879],
       [-0.53841446,  3.31179243, -0.71908481],
       [-0.17591934, -2.15359504,  0.69354038],
       [ 0.57229728,  1.17632623, -0.02990521]])

In [ ]:
np.save('array_random', array_2)

In [ ]:
read_array_2 = np.load('array_random.npy') # bu iikinchi fayl
read_array_2

array([[ 0.74686603, -0.45180601, -0.11406879],
       [-0.53841446,  3.31179243, -0.71908481],
       [-0.17591934, -2.15359504,  0.69354038],
       [ 0.57229728,  1.17632623, -0.02990521]])

In [ ]:
np.savez('array_s', a=array_1, b=array_2) # bu metod yordamida bir nechta array larni bir faylga yuklaymiz

In [ ]:
read_array_s = np.load('array_s.npz') # avval faylni o'zini chaqirib olamiz


In [ ]:
read_array_s['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
read_array_s['b']

array([[ 0.74686603, -0.45180601, -0.11406879],
       [-0.53841446,  3.31179243, -0.71908481],
       [-0.17591934, -2.15359504,  0.69354038],
       [ 0.57229728,  1.17632623, -0.02990521]])