<a href="https://colab.research.google.com/github/obidjonqunduzov/data-science/blob/main/3_indekslash_kesish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
array_1 = np.arange(2,20,2) # 2 dan 20 gacha 2 qadam bilan hisoblaydi
array_1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
block_1 = array_1[2] # shu ro'yxat ichidagi 2 indexga murojiat qiladi
block_1

6

In [ ]:
block_1 = array_1[2:4]
block_1[:] = 0 # 2 dan 4 gacha bolgan indexni 0 ga aylantiradi
block_1

array([0, 0])

In [ ]:
array_1 # biz o'zgartirgan index asl ro'yxatimizga ta'sir qiladi

array([ 2,  4,  2,  2, 10, 12, 14, 16, 18])

In [ ]:
array_2 = np.arange(10,100,10)
array_2

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
block_2 = array_2[2:5].copy()
block_2[:] = 0
block_2

array([0, 0, 0])

In [ ]:
array_2 # bu usul orqali asl ro'yxatimizga ta'sir etmaydi

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [3]:
array_3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
array_3[1,0:2]

array([4, 5])

In [5]:
array_3[1, 0:]

array([4, 5, 6])

In [8]:
array_4 = np.array([[[1,2,3],
                     [4,5,6],
                     [7,8,9]],

                    [[10,11,12],
                     [13,14,15],
                     [16,17,18],],

                    [[19,20,21],
                     [22,23,24],
                     [25,26,27]]])
array_4


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [10]:
array_4[1][0:2]

array([[10, 11, 12],
       [13, 14, 15]])

In [18]:
array_4[2][0, 0:2]

array([19, 20])