<a href="https://colab.research.google.com/github/obidjonqunduzov/data-science/blob/main/4_Boolean_Indekslash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

N - o'lchamli massivlarga ishlov berish

In [ ]:
names = np.array(['olim','obid','hasan','ali','vali'])
names

array(['olim', 'obid', 'hasan', 'ali', 'vali'], dtype='<U5')

In [ ]:
data_1 = np.random.randn(5, 3)
data_1

array([[-1.193449  , -0.30525552, -0.2905246 ],
       [-1.14789416,  0.05710541,  0.9307657 ],
       [ 0.62895588, -0.15613611, -0.60365674],
       [-0.70469338,  1.01841449,  1.76380079],
       [ 2.18720282, -1.20435624,  0.52941807]])

In [ ]:
names == 'olim' # bu olim ismini True qaytaradi qolganlarni False qaytaradi


array([ True, False, False, False, False])

In [ ]:
data_1[names == 'ali'] # ali ga tegishli ma'lumotlarni qaytaradi

array([[-1.28105405, -2.02224114, -1.49159087]])

In [ ]:
data_1[names=='hasan'] # hasanga tegishli ma'lumotlarni qaytaradi

array([[1.43591856, 0.90248432, 0.83007057]])

In [ ]:
data_1[names=='obid', 0:2] # obid ni ma'lumotlaridan 2 tasini ajratib oladi

array([[-0.24018792,  0.07876384]])

In [ ]:
data_1[names !='hasan'] # (!=) hasandan boshqa hammani ma'lumotini qaytaradi

array([[ 0.00996639, -1.37531759,  0.66792661],
       [ 0.49553033, -0.78022292,  0.26613168],
       [ 0.85091309,  1.28453401,  0.3589106 ],
       [-1.39470294,  0.71840381, -0.61290938]])

In [ ]:
data_1[~(names=='hasan')] #(~) bu ham hasan dan boshqa hammani ma'lumotlarini chiqaradi

array([[ 0.43549732, -0.31753116, -0.41179826],
       [-0.24018792,  0.07876384, -0.19195631],
       [-1.28105405, -2.02224114, -1.49159087],
       [-1.82608166, -1.69415547,  1.87765256]])

In [ ]:
print(names)
print(data_1)

['olim' 'obid' 'hasan' 'ali' 'vali']
[[-1.193449   -0.30525552 -0.2905246 ]
 [-1.14789416  0.05710541  0.9307657 ]
 [ 0.62895588 -0.15613611 -0.60365674]
 [-0.70469338  1.01841449  1.76380079]
 [ 2.18720282 -1.20435624  0.52941807]]


In [ ]:
mask = (names=='hasan') | (names=='ali') # "|" bu belgi or (yoki) deyiladi
mask

array([False, False,  True,  True, False])

In [ ]:
data_1[mask, 0:]

array([[ 0.62895588, -0.15613611, -0.60365674],
       [-0.70469338,  1.01841449,  1.76380079]])

In [ ]:
data_1

array([[-1.193449  , -0.30525552, -0.2905246 ],
       [-1.14789416,  0.05710541,  0.9307657 ],
       [ 0.62895588, -0.15613611, -0.60365674],
       [-0.70469338,  1.01841449,  1.76380079],
       [ 2.18720282, -1.20435624,  0.52941807]])

In [ ]:
data_1[data_1<0]=0 # bu 0 dan kichik manfiy sonlarni tashlab yuboradi
data_1

array([[0.        , 0.        , 0.        ],
       [0.        , 0.05710541, 0.9307657 ],
       [0.62895588, 0.        , 0.        ],
       [0.        , 1.01841449, 1.76380079],
       [2.18720282, 0.        , 0.52941807]])