<a href="https://colab.research.google.com/github/obidjonqunduzov/data-science/blob/main/5_Transpose_Swapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Massivlarni pozitsiyasini almashtirish uchun Transpose va Swapping dan foydalanamiz

In [1]:
import numpy as np

In [5]:
A = np.arange(6).reshape(3,2) # reshape bu qator va ustunlarni joylashtiradi
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
A.T # Transpose usuli yani (3,2) massivni (2,3) ko'rinishiga aylantiradi

array([[0, 2, 4],
       [1, 3, 5]])

In [11]:
A.swapaxes(1, 0) # bu ham aynan Transpose natijasini beradi, ammo birgina farqi bunda istalgancha massivlardan foydalansa bo'ladi


array([[0, 2, 4],
       [1, 3, 5]])

In [13]:
np.dot(A, A.T) # bu A ning A^T ning hosil bo'lgan massivi

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])