<a href="https://colab.research.google.com/github/obidjonqunduzov/data-science/blob/main/6_Universal_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array_1 = np.arange(11)
array_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(array_1) # array_1 elementlarini kvadrat ildizini hisoblaydi

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.square(array_1) # array_1 elementlarini har birini kvadrtaga ko'taradi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [5]:
np.exp(array_1) # array_1 elementlarini exponentini qaytaradi

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [7]:
np.log(array_1[1:]) # array_ elementlarini 0 dan boshqa hamma elementlarini logarifimini hisoblaydi

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [8]:
array_2 = np.random.randn(10)
array_2

array([ 0.76043135, -1.94589761, -0.75709616,  0.77604672, -0.29816195,
        0.40142324, -0.37888894,  0.36876321, -1.17845361,  0.02866188])

In [12]:
qoldiq, butun = np.modf(array_2)
print(qoldiq)
print(butun)

[ 0.76043135 -0.94589761 -0.75709616  0.77604672 -0.29816195  0.40142324
 -0.37888894  0.36876321 -0.17845361  0.02866188]
[ 0. -1. -0.  0. -0.  0. -0.  0. -1.  0.]


In [13]:
np.sign(array_2) # massiv elementlari qiymati manfiy bo'lsa -1 va aksincha musbat bo'lsa 1 qaytaradi

array([ 1., -1., -1.,  1., -1.,  1., -1.,  1., -1.,  1.])

isnan massivning elementlarida NaN ma'lumoti bo'lsa True qaytaradi va aksincha esa False qaytaradi

In [15]:
array_3 = np.random.randn(11)
array_3

array([-2.25003512, -0.03854534, -0.42658705, -0.47783732, -2.05395135,
       -0.10165905, -1.70863532,  2.21383247,  1.87688487,  0.46882973,
        0.77987787])

In [16]:
array_4 = np.random.randn(11)
array_4

array([-1.60509275, -0.82210201, -0.00818847, -2.03689138, -0.11414069,
       -1.66306582,  0.01515556, -0.3406288 ,  0.43954219,  1.30492579,
        0.58002649])

In [17]:
np.add(array_3, array_4) # bu funksiya ikkita massiv array_3 va array_4 larni qoshib beradi

array([-1.41522733, -2.32616723,  1.24711049, -2.29783007, -0.68489633,
       -2.21855284,  0.63588705, -1.91533   , -0.09888048, -0.2840348 ,
        0.54277032])

In [18]:
array_3 + array_4

array([-1.41522733, -2.32616723,  1.24711049, -2.29783007, -0.68489633,
       -2.21855284,  0.63588705, -1.91533   , -0.09888048, -0.2840348 ,
        0.54277032])

In [21]:
array_3

array([ 0.18986542, -1.50406522,  1.25529895, -0.26093869, -0.57075564,
       -0.55548702,  0.62073149, -1.5747012 , -0.53842268, -1.58896059,
       -0.03725617])

In [22]:
array_4

array([-1.60509275, -0.82210201, -0.00818847, -2.03689138, -0.11414069,
       -1.66306582,  0.01515556, -0.3406288 ,  0.43954219,  1.30492579,
        0.58002649])

In [23]:
np.multiply(array_3, array_4) # array_3 va array_4 massivlarini mos ravishda bir biriga ko'paytirib beradi

array([-0.30475161,  1.23649505, -0.01027897,  0.53150377,  0.06514644,
        0.92381147,  0.00940753,  0.53638858, -0.23665948, -2.07347566,
       -0.02160957])

In [28]:
np.maximum(array_4, array_3) # ikkita massivni taqqoslab eng kattasini qaytaradi

array([ 0.18986542, -0.82210201,  1.25529895, -0.26093869, -0.11414069,
       -0.55548702,  0.62073149, -0.3406288 ,  0.43954219,  1.30492579,
        0.58002649])