<a href="https://colab.research.google.com/github/obidjonqunduzov/data-science/blob/main/7_Logical_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Mantiqiy shart operatorlarni massiv operator sifatida qo'llash
Shart operatori sifatida where dan foydalanish
Tassavur qiling bizda ikkita ma'lumotlar (massivlar) mavjud bular: x_array va y_array. Agarda shart Trueni qanoatlantirsa xarr elementini qabul qilgan aksincha esa yarr elementini qabul qilgan yangi massiv hosil qilinsin.

In [7]:
# Massivlar
x_array = np.array([1.1, 1.2, 1.3, 1.4, 1.5, 1.6])
y_array = np.array([2.1, 2.2, 2.3, 2.4, 2.5, 2.6])


In [4]:
# Shart
cond = np.array([True, False, False, True, True, False])

In [8]:
# Where javobi
result = np.where(cond, x_array, y_array) # True - x_array elemntlarini, False - y_array elementlarini qaytaradi
result

array([1.1, 2.2, 2.3, 1.4, 1.5, 2.6])

In [10]:
array_1 =  np.random.randn(4,4)
array_1

array([[ 1.73732906, -0.01146962,  0.15122822,  1.24751406],
       [ 0.50438191, -0.37223886, -0.42117543, -0.99749819],
       [ 0.57021548, -1.0295535 ,  0.54649078,  0.95239884],
       [ 0.55985026,  0.04883657,  0.37354434,  0.94395288]])

In [11]:
result = np.where(array_1<0, -1, 1)
result

array([[ 1, -1,  1,  1],
       [ 1, -1, -1, -1],
       [ 1, -1,  1,  1],
       [ 1,  1,  1,  1]])