<a href="https://colab.research.google.com/github/obidjonqunduzov/data-science/blob/main/9_Math_stat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [6]:
array_1 = np.random.randn(5, 5)
array_1

array([[ 1.48863561, -0.26378149,  1.57586073, -1.11865808, -2.45774593],
       [-2.36609321,  0.51148766, -0.41963878,  0.77429308,  0.31730602],
       [-0.36412797,  2.13388152, -0.89662585, -0.66682765,  1.0146514 ],
       [ 0.53046828,  0.41661741, -0.19251367,  0.12523751, -0.50578376],
       [ 0.83867941,  0.7888193 , -0.89429961,  0.19644887,  1.56658057]])

In [7]:
array_1.sum() # array_1 massivning umumy elementlari yi'gindisi

2.1328713892577023

In [8]:
np.sum(array_1) # 2 chimusuli

2.1328713892577023

In [11]:
array_1.sum(axis = 1) # qatorlarni umumumy yi'gindisi

array([-0.77568916, -1.18264522,  1.22095146,  0.37402578,  2.49622854])

In [12]:
array_1.sum(axis = 0) # ustunlarni umumy yi'gindisi

array([ 0.12756212,  3.58702441, -0.82721718, -0.68950626, -0.0649917 ])

In [13]:
array_2 = np.arange(11)
array_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
array_2.mean() # array_2 massivining umumiy yi'gindisini o'z elementlar soniga bo'ladi

5.0

In [15]:
array_3 = np.random.randn(4, 4)
array_3

array([[-0.07924456, -0.80588258, -0.15080434,  0.89576414],
       [ 0.76292415,  1.8952787 , -0.16897409,  1.505274  ],
       [-0.38646644,  0.39416439, -0.14134672,  0.24120794],
       [ 0.39028516, -0.34968492, -1.31925336,  0.08371124]])

In [16]:
array_3.mean()

0.17293454444389708

In [17]:
array_3.mean(axis=1) # qator bo'yicha o'rtacha qiymat

array([-0.03504183,  0.99862569,  0.02688979, -0.29873547])

In [18]:
array_3.mean(axis=0) # ustun bo'yicha o'rtacha qiymat

array([ 0.17187458,  0.2834689 , -0.44509463,  0.68148933])

In [19]:
array_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
array_2.cumsum() # massiv elementlarini bir-biriga ketma-ket qoshib chiqaradi

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55])