<a href="https://colab.research.google.com/github/obidjonqunduzov/data-science/blob/main/Arithmetic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy kutubxonada qo'shish, ayirish, ko'paytirish, bo'lish ammalarini bajaramiz

In [21]:
import numpy as np

In [22]:
array_1 = np.arange(1, 7).reshape(2,3)
array_1

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
array_2 = np.arange(6, 12).reshape(2,3)
array_2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
array_1 + array_2 # ikkita massivlarni elementlarini qo'shish

array([[ 7,  9, 11],
       [13, 15, 17]])

In [25]:
array_2 - array_1 # ikkita massivlarini elementlarini ayirish

array([[5, 5, 5],
       [5, 5, 5]])

In [26]:
array_1 * array_2 # ikkita massivlarini elementlarini ko'paytirish

array([[ 6, 14, 24],
       [36, 50, 66]])

In [27]:
array_2 / array_1

array([[6.        , 3.5       , 2.66666667],
       [2.25      , 2.        , 1.83333333]])

In [28]:
array_1 ** 2 # kvadratga ko'taradi

array([[ 1,  4,  9],
       [16, 25, 36]])

In [31]:
np.square(array_2) # massivlarni kvadratga ko'tarish

array([[ 1,  4,  9],
       [16, 25, 36]])

In [33]:
np.sqrt(array_1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])