<a href="https://colab.research.google.com/github/obidjonqunduzov/data-science/blob/main/mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [ ]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
array_2 = np.array([1,2,3,4,5])
array_2
array_2.ndim

1

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [ ]:
array_3 = np.zeros((9,9))
array_3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
array_4 = np.arange(1,20,2)
array_4
np.size(array_4)

10

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
array_6 = np.zeros((12))
array_6[6]=1
array_6

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
array_7 = np.arange(20,59)
array_7

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
array_8 = np.array([1,2,3,4,5,6])
array_8[::-1]

array([6, 5, 4, 3, 2, 1])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
array_9 = np.arange(12,21).reshape(3, 3)
array_9

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
array_10 = np.array([3, 7, 0, 0, 9, 0])
np.nonzero(array_10)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
array_11 = np.random.randn(2,2,2)
array_11

array([[[ 0.32486874,  0.28128537],
        [-1.19749832,  0.71188004]],

       [[ 1.95854589, -1.53543914],
        [-0.14383925, -1.48672908]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
array_12 = np.random.randn(9,9)
array_12

array([[-0.2396614 ,  0.9798104 , -3.17884329,  0.16140674, -0.54340359,
        -1.44428802, -2.04799954, -0.84479423, -0.60170958],
       [-1.48568146, -0.38435133,  0.43762936,  1.35695497, -0.02209527,
        -1.33438247,  1.80302872, -1.42406217,  0.18164504],
       [ 0.12460205,  0.4146518 ,  0.08941208,  0.69060915, -0.54896297,
        -2.05223658, -0.08882497,  1.57369066,  1.49800746],
       [ 0.74091283, -0.97623755, -0.46447798, -0.48225626,  0.22644623,
         0.13146713, -1.32404459,  2.1057169 ,  0.22048745],
       [ 1.12210203, -1.19617106, -0.13180521,  1.1272859 , -1.58487402,
        -0.73768138, -0.09072157, -0.07259188,  0.8239743 ],
       [ 0.1248869 , -0.48333329,  0.65773186,  1.40990071, -1.58822795,
        -0.70909011, -1.8379881 ,  0.13914778, -1.00854088],
       [-0.56479401, -0.95307545,  0.09872641, -0.90400157,  0.51394005,
         0.77678997, -0.39381393, -0.87152653,  0.10171012],
       [-0.63810803, -0.26285436,  1.73211275, -0.57216027, -0

In [ ]:
np.max(array_12)

2.1057168997420797

In [ ]:
np.min(array_12)

-3.1788432916016136

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
a_array_14 = np.eye(6,3)
a_array_14

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b_array_14 = np.eye(3,4)
b_array_14

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
np.dot(a_array_14, b_array_14)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
a_array_16 = np.array([1 , 2])

In [ ]:
b_array_16 = np.array([4 , 5])

In [ ]:
a_array_16 > b_array_16

array([False, False])

In [ ]:
a_array_16 >= b_array_16

array([False, False])

In [ ]:
a_array_16 < b_array_16

array([ True,  True])

In [ ]:
a_array_16 <= b_array_16

array([ True,  True])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-66-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-66-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
a_array_18 = np.arange(1,10)
b_array_18 = np.arange(5,20)
np.intersect1d(a_array_18,b_array_18)

array([5, 6, 7, 8, 9])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
array_19 = np.random.randn(3,3)
array_19

array([[ 1.0579252 ,  0.13588834, -0.6216451 ],
       [ 1.78768085,  0.84866894, -0.94729865],
       [-0.40499335,  0.49992021,  0.67591225]])

In [ ]:
np.floor(array_19)

array([[ 1.,  0., -1.],
       [ 1.,  0., -1.],
       [-1.,  0.,  0.]])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:
array_20 = np.eye(3,3) # ???

array_20

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
array_21 = np.random.randn(10)
array_21.sort()
array_21

array([-0.54835182, -0.44274778, -0.38706687, -0.11165357,  0.39847758,
        0.58544827,  0.83283008,  0.95025028,  1.28983198,  1.62927839])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [ ]:
a_array_22 = np.random.randn(5)
b_array_22 = np.random.randn(5)
np.array_equal(a_array_22, b_array_22)

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [ ]:
a_array_23 = np.eye(6,3)
b_array_23 = np.eye(3,4)
np.dot(a_array_23,b_array_23)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [ ]:
array_24 = np.random.randn(5)
np.argmax(array_24)==0

False

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
import datetime as dt
bugun = np.datetime64('Today')
bugun

numpy.datetime64('2024-02-06')

In [ ]:
kecha = bugun - 1
kecha

numpy.datetime64('2024-02-05')

In [ ]:
ertaga = bugun + 1
ertaga

numpy.datetime64('2024-02-07')

#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
array_26 = np.arange('2016-01', '2016-02', dtype='datetime64[D]')
array_26

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [ ]:
array_27 = np.random.randn(3,3)
np.floor(array_27>0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float16)

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [ ]:
a_array = np.random.randn(100)
summ = np.sum
summ(a_array)


18.690589230770026

In [ ]:
b_array = np.random.randn(100)
summ_2 = np.add.reduce
summ_2(b_array)

-11.820421536149038

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [ ]:
array_29 = np.array( [1, 2, 3, 4, 5])
array_29[::4]=0

array_29


array([0, 2, 3, 4, 0])

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [ ]:

array_30 =([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
np.lib.stride_tricks.sliding_window_view(array_30, 4)

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [ ]:
np.bincount(np.arange(10))


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.bincount(np.array([1,4,5,8,9]))

array([0, 1, 0, 0, 1, 1, 0, 0, 1, 1])

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

In [ ]:
# Ramazon oyigacha taxminan qancha vaqt qoldi? Boshlanish muddati taxminan 11 mart deb olamiz

bugun = np.datetime64('Today')
ramazon = np.datetime64('2024-03-11')
farq = ramazon - bugun
farq = (f"Ramazon kunigacha {ramazongacha} qoldi")
farq

'Ramazon kunigacha 34 days qoldi'